import type { Shipment } from "./types";

// Timestamps are generated relative to the moment the store is seeded so the
// sample data always looks current in a demo.
const now = Date.now();
const HOUR = 60 * 60 * 1000;
const at = (hoursFromNow: number) => new Date(now + hoursFromNow * HOUR).toISOString();

export function buildSeedShipments(): Shipment[] {
  return [
    {
      trackingNumber: "STS-2026-00042",
      status: "in_transit",
      service: "express",
      customerName: "Priya Nair",
      customerEmail: "priya.nair@boltmart.example",
      customerPhone: "+1 (214) 555-0142",
      origin: { city: "Dallas", state: "TX" },
      destination: { city: "Houston", state: "TX" },
      pieces: 3,
      weightKg: 46,
      currentLocation: "Corsicana, TX",
      createdAt: at(-30),
      estimatedDelivery: at(8),
      events: [
        { status: "booked", location: "Dallas, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-30) },
        { status: "picked_up", location: "Dallas, TX", note: "Collected from the shipper.", timestamp: at(-26) },
        { status: "in_transit", location: "Dallas sort facility", note: "Departed the origin facility.", timestamp: at(-22) },
        { status: "in_transit", location: "Corsicana, TX", note: "In transit through Corsicana, TX.", timestamp: at(-6) },
      ],
    },
    {
      trackingNumber: "STS-2026-00039",
      status: "delivered",
      service: "standard",
      customerName: "Elena Brooks",
      customerEmail: "elena.brooks@nextlevelretail.example",
      customerPhone: "+1 (512) 555-0198",
      origin: { city: "Austin", state: "TX" },
      destination: { city: "San Antonio", state: "TX" },
      pieces: 1,
      weightKg: 12,
      currentLocation: "San Antonio, TX",
      createdAt: at(-54),
      estimatedDelivery: at(-27),
      events: [
        { status: "booked", location: "Austin, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-54) },
        { status: "picked_up", location: "Austin, TX", note: "Collected from the shipper.", timestamp: at(-50) },
        { status: "in_transit", location: "Austin hub", note: "Departed the origin facility.", timestamp: at(-46) },
        { status: "out_for_delivery", location: "San Antonio, TX", note: "Loaded for final delivery.", timestamp: at(-30) },
        { status: "delivered", location: "San Antonio, TX", note: "Delivered to the front desk.", timestamp: at(-28) },
      ],
      proofOfDelivery: {
        signedBy: "M. Reyes",
        deliveredAt: at(-28),
        photoNote: "Left with front desk reception.",
      },
    },
    {
      trackingNumber: "STS-2026-00051",
      status: "out_for_delivery",
      service: "freight",
      customerName: "Sam Whitfield",
      customerEmail: "s.whitfield@prairiesupply.example",
      customerPhone: "+1 (817) 555-0173",
      origin: { city: "Fort Worth", state: "TX" },
      destination: { city: "Oklahoma City", state: "OK" },
      pieces: 6,
      weightKg: 240,
      currentLocation: "Oklahoma City, OK",
      createdAt: at(-40),
      estimatedDelivery: at(4),
      events: [
        { status: "booked", location: "Fort Worth, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-40) },
        { status: "picked_up", location: "Fort Worth, TX", note: "Collected from the shipper.", timestamp: at(-34) },
        { status: "in_transit", location: "Fort Worth freight terminal", note: "Departed the origin terminal.", timestamp: at(-30) },
        { status: "in_transit", location: "Ardmore, OK", note: "In transit through Ardmore, OK.", timestamp: at(-14) },
        { status: "out_for_delivery", location: "Oklahoma City, OK", note: "Loaded for final delivery.", timestamp: at(-3) },
      ],
    },
    {
      trackingNumber: "STS-2026-00047",
      status: "picked_up",
      service: "standard",
      customerName: "Grace Adeyemi",
      customerEmail: "grace@bayoucrafts.example",
      customerPhone: "+1 (469) 555-0121",
      origin: { city: "Dallas", state: "TX" },
      destination: { city: "New Orleans", state: "LA" },
      pieces: 2,
      weightKg: 28,
      currentLocation: "Dallas, TX",
      createdAt: at(-12),
      estimatedDelivery: at(36),
      events: [
        { status: "booked", location: "Dallas, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-12) },
        { status: "picked_up", location: "Dallas, TX", note: "Collected from the shipper.", timestamp: at(-6) },
      ],
    },
    {
      trackingNumber: "STS-2026-00055",
      status: "booked",
      service: "express",
      customerName: "Tom Delgado",
      customerEmail: "tom.delgado@harborfoods.example",
      customerPhone: "+1 (713) 555-0155",
      origin: { city: "Houston", state: "TX" },
      destination: { city: "Memphis", state: "TN" },
      pieces: 4,
      weightKg: 63,
      currentLocation: "Houston, TX",
      createdAt: at(-3),
      estimatedDelivery: at(30),
      events: [
        { status: "booked", location: "Houston, TX", note: "Booking confirmed. Pickup scheduled for this afternoon.", timestamp: at(-3) },
      ],
    },
    {
      trackingNumber: "STS-2026-00033",
      status: "delivered",
      service: "freight",
      customerName: "Nadia Farouk",
      customerEmail: "nadia.farouk@desertparts.example",
      customerPhone: "+1 (915) 555-0188",
      origin: { city: "El Paso", state: "TX" },
      destination: { city: "Phoenix", state: "AZ" },
      pieces: 8,
      weightKg: 310,
      currentLocation: "Phoenix, AZ",
      createdAt: at(-96),
      estimatedDelivery: at(-49),
      events: [
        { status: "booked", location: "El Paso, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-96) },
        { status: "picked_up", location: "El Paso, TX", note: "Collected from the shipper.", timestamp: at(-90) },
        { status: "in_transit", location: "El Paso freight terminal", note: "Departed the origin terminal.", timestamp: at(-84) },
        { status: "in_transit", location: "Tucson, AZ", note: "In transit through Tucson, AZ.", timestamp: at(-60) },
        { status: "out_for_delivery", location: "Phoenix, AZ", note: "Loaded for final delivery.", timestamp: at(-50) },
        { status: "delivered", location: "Phoenix, AZ", note: "Delivered to the loading dock.", timestamp: at(-48) },
      ],
      proofOfDelivery: {
        signedBy: "D. Okafor",
        deliveredAt: at(-48),
        photoNote: "Offloaded at dock 4.",
      },
    },
    {
      trackingNumber: "STS-2026-00058",
      status: "exception",
      service: "standard",
      customerName: "Owen Clarke",
      customerEmail: "owen.clarke@summitgear.example",
      customerPhone: "+1 (210) 555-0164",
      origin: { city: "San Antonio", state: "TX" },
      destination: { city: "Denver", state: "CO" },
      pieces: 2,
      weightKg: 34,
      currentLocation: "Raton, NM",
      createdAt: at(-60),
      estimatedDelivery: at(20),
      events: [
        { status: "booked", location: "San Antonio, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-60) },
        { status: "picked_up", location: "San Antonio, TX", note: "Collected from the shipper.", timestamp: at(-54) },
        { status: "in_transit", location: "San Antonio hub", note: "Departed the origin facility.", timestamp: at(-48) },
        { status: "in_transit", location: "Amarillo, TX", note: "In transit through Amarillo, TX.", timestamp: at(-30) },
        { status: "exception", location: "Raton, NM", note: "Delayed by weather near Raton Pass. A revised delivery estimate has been issued.", timestamp: at(-10) },
      ],
    },
    {
      trackingNumber: "STS-2026-00060",
      status: "in_transit",
      service: "express",
      customerName: "Bianca Rossi",
      customerEmail: "bianca@riverbendco.example",
      customerPhone: "+1 (972) 555-0139",
      origin: { city: "Dallas", state: "TX" },
      destination: { city: "Kansas City", state: "MO" },
      pieces: 1,
      weightKg: 9,
      currentLocation: "Tulsa, OK",
      createdAt: at(-20),
      estimatedDelivery: at(10),
      events: [
        { status: "booked", location: "Dallas, TX", note: "Booking confirmed and scheduled for pickup.", timestamp: at(-20) },
        { status: "picked_up", location: "Dallas, TX", note: "Collected from the shipper.", timestamp: at(-16) },
        { status: "in_transit", location: "Dallas sort facility", note: "Departed the origin facility.", timestamp: at(-12) },
        { status: "in_transit", location: "Tulsa, OK", note: "In transit through Tulsa, OK.", timestamp: at(-3) },
      ],
    },
  ];
}
