import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";

import { Logo } from "@/components/Logo";
import { PrintButton } from "@/components/PrintButton";
import { formatDateTime, placeLabel } from "@/lib/format";
import { getShipment } from "@/lib/store";

interface PageProps {
  params: { trackingNumber: string };
}

export function generateMetadata({ params }: PageProps): Metadata {
  const tn = decodeURIComponent(params.trackingNumber).toUpperCase();
  return { title: `Proof of delivery — ${tn}` };
}

export default function PodPage({ params }: PageProps) {
  const trackingNumber = decodeURIComponent(params.trackingNumber);
  const shipment = getShipment(trackingNumber);

  if (!shipment || !shipment.proofOfDelivery) {
    notFound();
  }

  const pod = shipment.proofOfDelivery;

  return (
    <div className="min-h-screen bg-slate-100 py-10 print:bg-white print:py-0">
      <div className="mx-auto max-w-2xl px-5">
        <div className="no-print mb-4 flex items-center justify-between">
          <Link
            href={`/track/${encodeURIComponent(shipment.trackingNumber)}`}
            className="text-sm font-medium text-brand-600 hover:text-brand-700"
          >
            ← Back to tracking
          </Link>
          <PrintButton />
        </div>

        <article className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm print:border-0 print:shadow-none">
          <header className="flex items-start justify-between border-b border-slate-200 pb-6">
            <Logo />
            <div className="text-right">
              <h1 className="text-lg font-bold tracking-tight text-slate-900">
                Proof of Delivery
              </h1>
              <p className="text-sm text-slate-500">{shipment.trackingNumber}</p>
            </div>
          </header>

          <div className="mt-6 grid grid-cols-2 gap-6 text-sm">
            <Field label="From" value={placeLabel(shipment.origin)} />
            <Field label="To" value={placeLabel(shipment.destination)} />
            <Field label="Recipient" value={shipment.customerName} />
            <Field label="Service" value={shipment.service === "freight" ? "Freight (LTL)" : shipment.service === "express" ? "Express" : "Standard"} />
            <Field label="Pieces" value={String(shipment.pieces)} />
            <Field label="Weight" value={`${shipment.weightKg} kg`} />
          </div>

          <div className="mt-6 rounded-xl bg-emerald-50 p-5">
            <div className="grid grid-cols-2 gap-6 text-sm">
              <Field label="Delivered" value={formatDateTime(pod.deliveredAt)} accent />
              <Field label="Signed by" value={pod.signedBy} accent />
            </div>
            <p className="mt-3 text-sm text-emerald-800">{pod.photoNote}</p>
          </div>

          <footer className="mt-8 border-t border-slate-200 pt-4 text-xs text-slate-400">
            This receipt confirms delivery of the shipment referenced above.
            Generated by Sky Transport Solutions on {formatDateTime(new Date().toISOString())}.
          </footer>
        </article>
      </div>
    </div>
  );
}

function Field({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) {
  return (
    <div>
      <dt className={`text-xs uppercase tracking-wider ${accent ? "text-emerald-700/70" : "text-slate-400"}`}>
        {label}
      </dt>
      <dd className={`mt-0.5 font-medium ${accent ? "text-emerald-900" : "text-slate-900"}`}>
        {value}
      </dd>
    </div>
  );
}
